### ISSUE TITLE
Error on DynamicTileMerge 'image_width' is not defined

### ISSUE THREAD

**Issue by alcaitiff** [kinfolk0117/ComfyUI_SimpleTiles#4]
On ComfyUI_SimpleTiles/dynamic.py you doubled the call below

```python
        tile_coordinates = generate_tiles(
            final_width, final_height, tile_width, tile_height, overlap, offset
        )
        tile_coordinates = generate_tiles(
            image_width, image_height, tile_width, tile_height, overlap, offset
        )
```

Error:

```log
got prompt
Tile height: 512
Tile width: 512
Final height: 4912
Final width: 2448
Overlap: 128
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/media/AI/ComfyUI/execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/media/AI/ComfyUI/execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/media/AI/ComfyUI/execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/media/AI/ComfyUI/custom_nodes/ComfyUI_SimpleTiles/dynamic.py", line 151, in process
    #     image_width, image_height, tile_width, tile_height, overlap, offset
NameError: name 'image_width' is not defined
```

I manually removed the second call and it works

**Comment by kinfolk0117** [comment]
Thanks! Fixed in 584053f8aed67e5897d5e41c7e71dbb4e1dfb654
